config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  root 'tasks#index'
  
  resources :users
  get 'users/new'

  resources :tasks do
    collection do
      get 'completed' => 'tasks#completed'
      get 'deleted' => 'tasks#deleted'
      get 'search' => 'tasks#search'
      post 'search' => 'tasks#search'
    end
    
    member do
      patch 'edit_completed' => 'tasks#edit_completed'
      patch 'pre_destroy' => 'tasks#pre_destroy'
    end
  end

  resources :projects do
    resources :tasks, controller: 'projects/tasks'
  end

  get '/login/index' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
  get '/login/guest' => 'sessions#login_as_guest'

  get '/admin' => 'admin#index'
  get '/admin/users' => 'admin#users_show'
  get '/admin/tasks' => 'admin#tasks_show'

  post '/callback' => 'linebot#callback'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true

  with_options presence: true do
    validates :title
    validates :content
    validates :timelimit
  end

end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController

  before_action :require_login

  def show
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def require_login
      unless logged_in?
        flash[:danger] = "Please login!"
        redirect_to login_path
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    
  include Common
  before_action :require_login

  def index
    @tasks = task_common
  end

  def new
  end

  def create
    @task = current_user.tasks.build(tasks_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path , flash: { success: "Task was successfully created" } }
        format.json { render :index, status: :created, location: @task }
      else
        flash.now[:danger] = "Create task was failed"
        format.html { render 'new' }
        format.json { render json: @task.errors }
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(tasks_params)
      redirect_to root_path, flash: { success: "Success to be updated" }
    end
  end

  def completed
    @tasks = task_common('completed')
  end

  def edit_completed
    @task = Task.find(params[:id])
    is_completed = @task.completed
    if @task.update_attributes(completed: !is_completed)
      if status(@task) == 'completed'
        redirect_to completed_tasks_path, flash: { success: "Success to change completed" }
      else
        redirect_to root_path, flash: { success: "Success to change incompleted" }
      end
    end
  end

  def deleted
    @tasks = task_common('deleted')
  end

  def pre_destroy
    @task = Task.find(params[:id])
    is_deleted = @task.deleted
    if @task.update_attributes(deleted: !is_deleted)
      if status(@task) == 'deleted'
        redirect_to deleted_tasks_path, flash: { danger: "Success to destroy" }
      else
        redirect_to root_path, flash: { success: "Success to Restore!!" }
      end
    end
  end

  def destroy
    if Task.find(params[:id]).destroy!
      redirect_to deleted_tasks_path, flash: { danger: "Task completelly destroy!!" }
    end
  end

  def search
    @tasks = current_user.tasks.all
    @search = Task.ransack(params[:q])
    @search_tasks = @search.result(distinct: true)

    respond_to do |format|
      format.json {
        render json: @search_tasks
      }
      format.html
    end
  end

  private

    def tasks_params
      params.require(:task).permit(:title, :content, :timelimit, :completed, :deleted, :user_id, :project_id)
    end

    def require_login
      unless logged_in?
        flash[:danger] = "Please login!"
        redirect_to login_path
      end
    end
end

app/helpers/projects/tasks_helper.rb
module Projects::TasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def owner(task)
    id = task.user_id
    user = User.find(task.user_id)
    @owner = user.name
  end

  def search_tasks
    @tasks = current_user.tasks.all.order(timelimit: 'DESC').where(completed: false, deleted: false).paginate(page: params[:page], per_page: 5)
    @search = @tasks.ransack(params[:q])
    @search_tasks = @search.result
  end

  def status(task)
    if task.deleted
      return 'deleted'
    elsif task.completed
      return 'completed'
    else
      return 'neutral'
    end
  end
end

app/views/tasks/_search_tasks.html.erb
<div>
  <table class="table mt-2">
    <tr>
      <td>Title</td>
      <td>Content</td>
      <td>Timelimit</td>
      <td>Completed</td>
      <td>Deleted</td>
    </tr>
    <% task.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.timelimit %></td>
        <td><%= task.completed %></td>
        <td><%= task.deleted %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/tasks/_task_content.html.erb
<div class='text-muted mt-1 mb-2'><%= task.content %></div>
<div class='text-muted mt-1 mb-2'><%= task.timelimit %></div>
<div class='text-muted mt-1 mb-2'><%= task.completed %></div>

app/views/tasks/_tasks.html.erb
<div>
  <span>
    <%= button_to '+ New Task', new_task_path, class:"btn btn-bg btn-success", method: :get %>
  </span>
  <table class="table mt-2">
    <thead>
      <tr>
        <td><h3>Task List</h3></td>
      </tr>
    </thead>
    <tr>
      <td>Title</td>
      <td>Content</td>
      <td>Timalimit</td>
    </tr>
    <% @tasks.each do |task| %>
      <% if status(task) == 'neutral' %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.timelimit %></td>
          <td><%= link_to "Edit", edit_task_path(task), method: :get, class: "text-info" %></td>
          <td><%= link_to "Complete", edit_completed_task_path(task), method: :patch, class: "text-success" %></td>
          <td><%= link_to "Delete", pre_destroy_task_path(task), method: :patch, class: "text-danger", data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/tasks/completed.html.erb
<table class="table mt-2">
  <thead>
    <tr>
      <td><h3>Completed List</h3></td>
    </tr>
  </thead>
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Timalimit</td>
  </tr>
  <% @tasks.each do |task| %>
    <% if status(task) == 'completed' %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.timelimit %></td>
        <td><%= link_to "Edit", edit_task_path(task), method: :get, class: "text-info" %></td>
        <td><%= link_to "InComplete", edit_completed_task_path(task), method: :patch, class: "text-success" %></td>
        <td><%= link_to "Delete", pre_destroy_task_path(task), method: :patch, class: "text-danger", data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= will_paginate(@tasks, class: "pagination justify-content-center text-muted m-5")  if @tasks.present? %>

app/views/tasks/deleted.html.erb
<table class="table mt-2">
  <thead>
    <tr>
      <td><h3>Deleted List</h3></td>
    </tr>
  </thead>
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Timalimit</td>
  </tr>
  <% @tasks.each do |task| %>
    <% if status(task) == 'deleted' %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.timelimit %></td>
        <td><%= link_to "Edit", edit_task_path(task), method: :get, class: "text-info" %></td>
        <td><%= link_to "Restore", pre_destroy_task_path(task), method: :patch, class: "text-success" %></td>
        <td><%= link_to "Destroy", task_path(task), method: :delete, class: "text-danger", data: { confirm: "Completelly Delete, Are you sure?" } %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= will_paginate(@tasks, class: "pagination justify-content-center text-muted m-5")  if @tasks.present? %>

app/views/tasks/edit.html.erb
<table class="table text-center text-muted">
  <%= form_with(scope: :task, url: task_path, local: true) do |f| %>
    <thead>
      <tr>
        <td><h3 class="mt-3">Edit Task</h3></td>
      </tr>
    </thead>
    <tr>
      <td>Title</td>
      <td><%= f.text_field :title, autocomplete: 'off', class: 'form-control' %></td>
    </tr>
    <tr>
      <td>Content </td>
      <td><%= f.text_area :content, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= f.submit "Save", method: :patch, class: 'btn btn-sm btn-primary form-control' %></td>
      <td><%= link_to 'cancel', tasks_path, class:"text-reset text-muted" %></td>
    </tr>
  <% end %>
</table>

app/views/tasks/index.html.erb
<%= render 'tasks', task: @tasks %>

<%= will_paginate @tasks if @tasks.present? %>

app/views/tasks/new.html.erb
<table class="table text-center text-muted">
  <%= form_with(scope: :task, url: tasks_path, local: true) do |f| %>
    <thead>
      <tr>
        <td><h3 class="mt-3">New Task</h3></td>
      </tr>
    </thead>
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title, autocomplete: 'off' %></td>
    </tr>
    <tr>
      <td><%= f.label :content %></td>
      <td><%= f.text_area :content %></td>
    </tr>
    <tr>
      <td><%= f.label :Limit %></td>
      <td><%= f.date_field :timelimit %></td>
    </tr>
    <tr>
      <td><%= f.label :Project %></td>
      <td><%= f.select :project_id, Project.all.map {|project| [ project.project_name, project.id ]}%></td>
    </tr>
    <tr>
      <td><%= f.submit "submit", class:"btn btn-sm btn-primary" %></td>
      <td><%= link_to "cancel", tasks_path, class:"text-reset text-muted" %></td>
    </tr>
  <% end %>
</table>

app/views/tasks/search.html.erb
<h1>タスク検索</h1>
<table class="table">
  <%= search_form_for(@search, url: search_tasks_path, method: :post ) do |f| %>
    <thead></thead>
    <tbody>
      <tr>
        <td><%= f.label :title, "title" %></td>
        <td><%= f.search_field :title_cont, id: "search_title", class: "mr-sm-2"%></td>
        <td><%= f.label :content, "content" %></td>
        <td><%= f.search_field :content_cont, class: "mr-sm-2 mr-5" %></td>
      </tr>
      <tr>
        <td><%= f.label :created_at_gteq, "From" %></td>
        <td><%= f.date_field :created_at_gteq %></td>
        <td><%= f.label :created_at_lteq, "to here" %></td>
        <td><%= f.date_field :created_at_lteq %></td>
      </tr>
      <tr>
        <td><%= f.submit "Search",  class:"btn btn-sm my-2 my-sm-0" %></td>
        <td><%= link_to "Reset", search_tasks_path, method: :get, class:"btn btn-default text-muted"%></td>
      </tr>
    </tbody>
  <% end %>
</table>

<%= render 'search_tasks', task: @search_tasks %>