config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  root 'tasks#index'
  
  resources :users
  get 'users/new'

  resources :tasks do
    collection do
      get 'completed' => 'tasks#completed'
      get 'deleted' => 'tasks#deleted'
      get 'search' => 'tasks#search'
      post 'search' => 'tasks#search'
    end
    
    member do
      patch 'edit_completed' => 'tasks#edit_completed'
      patch 'pre_destroy' => 'tasks#pre_destroy'
    end
  end

  resources :projects do
    resources :tasks, controller: 'projects/tasks'
  end

  get '/login/index' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
  get '/login/guest' => 'sessions#login_as_guest'

  get '/admin' => 'admin#index'
  get '/admin/users' => 'admin#users_show'
  get '/admin/tasks' => 'admin#tasks_show'

  post '/callback' => 'linebot#callback'
end

app/views/admin/_index_left.html.erb
<nav class="sidebar mt-5">
  <div class="sidebar-sticky">
    <h3>Admin Console</h3>
  </div>
  <ul class="nav flex-column list-unstyled navbar-fixed-left" data-spy="affix" data-offset-top="205">
    <li class="nav-item">
      <%= link_to "Tasks", admin_tasks_path, method: :get, class:"nav-link" %>
      <span class="sr-only">(current)</span>
    </li>
    <li class="nav-item">
      <%= link_to "Users", admin_users_path, method: :get, class:"nav-link" %>
    </li>
  </ul>
</nav>

app/views/admin/index.html.erb
<h3 class="mt-5">Latest Update</h3>
<table class="table">
  <tr>
    <td>Title</td>
    <td>Updated</td>
    <td>Owner</td>
  </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.updated_at %></td>
      <td><%= owner(task)%></td>
    </tr>
  <% end %>
</table>
<h3 class="mt-5">Weekly Create Task Graf</h3>
<%= line_chart @graf.group_by_day_of_week(:created_at, format: "%a").count, xtitle: "Day", ytitle: "Count", suffix: "t", messages: {empty: "No data"}  %>

app/views/admin/tasks_show.html.erb
<h3 class="mt-5 mb-3">All Tasks List</h3>

<table class="table">
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Timalimit</td>
    <td>Owner</td>
  </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.timelimit %></td>
      <td><%= owner(task) %></td>
      <td><%= link_to "Edit", edit_task_path(task), method: :get, class: "text-info" %></td>
      <td><%= link_to "Delete", task, method: :delete, class: "text-danger", data: { confirm: "You sure?" } %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @tasks %>

app/views/admin/users_show.html.erb
<h3 class="mt-5 mb-3">All Users List</h3>

<table class="table">
  <tr>
    <td>Name</td>
    <td>Email</td>
    <td>Admin</td>
    <td>Task</td>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin %></td>
      <td><%= user.tasks.count %></td>
      <td><%= link_to 'edit', edit_user_path(user), class: "text-info" %></td>
      <td><%= link_to 'Delete', user_path(user), method: :delete, class: "text-danger", data: { confirm: "You sure?" } %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @users %>