config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  root 'tasks#index'
  
  resources :users
  get 'users/new'

  resources :tasks do
    collection do
      get 'completed' => 'tasks#completed'
      get 'deleted' => 'tasks#deleted'
      get 'search' => 'tasks#search'
      post 'search' => 'tasks#search'
    end
    
    member do
      patch 'edit_completed' => 'tasks#edit_completed'
      patch 'pre_destroy' => 'tasks#pre_destroy'
    end
  end

  resources :projects do
    resources :tasks, controller: 'projects/tasks'
  end

  get '/login/index' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
  get '/login/guest' => 'sessions#login_as_guest'

  get '/admin' => 'admin#index'
  get '/admin/users' => 'admin#users_show'
  get '/admin/tasks' => 'admin#tasks_show'

  post '/callback' => 'linebot#callback'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user, optional: true
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController

  before_action :require_login

  def show
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def require_login
      unless logged_in?
        flash[:danger] = "Please login!"
        redirect_to login_path
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login

  def show
    @project = Project.find(params[:id])
  end

  def index
    @projects = current_user.projects.all
  end

  def new
  end

  def create
    @project = current_user.projects.build(project_params)
    
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, flash: { success: "Project was successfully created" } }
        format.js { render :index, status: :created, location: @project }
      else
        flash.now[:danger] = "Create project was failed"
        format.html { render 'new' }
        format.js { reeder json: @project.errors }
      end
    end 
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to projects_path, flash: { success: "Project was successfully updated!!" }
    end
  end

  def destroy
    if @project = Project.find(params[:id]).destroy!
      redirect_to projects_path, flash: { danger: "Task completelly destroy!!" }
    end
  end

  private

    def project_params
      params.require(:projects).permit(:project_name, :user_id)
    end

    def require_login
      unless logged_in?
        flash[:danger] = "Please login!"
        redirect_to login_path
      end
    end
end

app/helpers/projects/tasks_helper.rb
module Projects::TasksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_left.html.erb
<nav class="sidebar mt-5">
  <div class="sidebar-sticky">
    <h3>Projects</h3>
  </div>
  <ul class="nav flex-column list-unstyled navbar-fixed-left" data-spy="affix" data-offset-top="205">
    <% @user_project.each do |p| %>
      <li class="nav-item">
        <%= link_to "#{p.project_name}", project_path(p), class:"text-muted" %>
        <span class="sr-only">(current)</span>
      </li>
    <% end %>
  </ul>
</nav>

app/views/projects/edit.html.erb
<table class="table">
  <%= form_with(scope: :projects, url: project_path, method: :patch, local: true) do |p| %>
    <thead>
      <tr>
        <td><h3>Edit Project</h3></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= p.label :project_name %></td>
        <td><%= p.text_field :project_name %></td>
      </tr>
      <tr>
        <td><%= p.submit %></td>
        <td><%= link_to "cancel", projects_path, method: :get %></td>
      </tr>
    </tbody>
  <% end%>
</table>

app/views/projects/index.html.erb
<%= link_to "+ New Project", new_project_path, class:"btn btn-bg btn-success" %>

<table class="table mt-2">
  <tbody>
    <tr>
      <td><h3>Project Name</h3></td>
    </tr>
    <% @projects.each do |p| %>
      <tr>
        <td><%= p.project_name %></td>
        <td><%= link_to "Detail", project_path(p), method: :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<table class="table">
  <%= form_with(scope: :projects, url: projects_path, method: :post, local: true) do |p| %>
    <thead>
      <tr>
        <td><h3>New Project</h3></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= p.label :project_name %></td>
        <td><%= p.text_field :project_name %></td>
      </tr>
      <tr>
        <td><%= p.submit %></td>
        <td><%= link_to "cancel", projects_path, method: :get %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/projects/show.html.erb
<table class="table mt-2">
  <tbody>
    <tr>
      <td><h3>Project Name</h3></td>
    </tr>
    <tr>
      <td><%= @project.project_name %></td>
      <td><%= link_to "Edit", edit_project_path(@project), method: :get %></td>
      <td><%= link_to "Delete", project_path(@project), method: :delete, class:"text-danger" %></td>
    </tr>
  </tbody>
</table>
<table class="table mt-5">
  <tbody>
    <tr>
      <td><h5>Associate Tasks</h5></td>
    </tr>
    <tr>
      <td>Title</td>
      <td>Content</td>
      <td>Timelimit</td>
    </tr>
    <% if !@project.tasks.empty? %>
      <% @project.tasks.each do |t| %>
        <tr>
          <td><%= link_to "#{t.title}", project_task_path(@project, t) %></td>
          <td><%= t.content %></td>
          <td><%= t.timelimit %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td>No Contents</td>
        <td>-</td>
        <td>-</td>
      </tr>
    <% end %>
  </tbody>
</table>