config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  root 'tasks#index'
  
  resources :users
  get 'users/new'

  resources :tasks do
    collection do
      get 'completed' => 'tasks#completed'
      get 'deleted' => 'tasks#deleted'
      get 'search' => 'tasks#search'
      post 'search' => 'tasks#search'
    end
    
    member do
      patch 'edit_completed' => 'tasks#edit_completed'
      patch 'pre_destroy' => 'tasks#pre_destroy'
    end
  end

  resources :projects do
    resources :tasks, controller: 'projects/tasks'
  end

  get '/login/index' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
  get '/login/guest' => 'sessions#login_as_guest'

  get '/admin' => 'admin#index'
  get '/admin/users' => 'admin#users_show'
  get '/admin/tasks' => 'admin#tasks_show'

  post '/callback' => 'linebot#callback'
end

app/views/head/_header.html.erb
<nav id="header" class="navbar navbar-expand-lg navbar-light text-light">
  <% if !admin? %>
    <%= link_to 'Todo', root_path, method: :get, class:"navbar-brand text-light" %>
  <% else %>
    <%= link_to 'Todo', admin_index_path, method: :get, class:"navbar-brand text-light"%>
  <% end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="btn-group">
        <button type="button" class="btn btn-success btn-sm dropdown-toggle dropdown-toggle-split"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">ドロップダウンの切替</span>
        </button>
        <div class="dropdown-menu">
          <div>
            <%= link_to "User", users_path, method: :get, class:"nav-link" if !guest?%>
          </div>
          <div>
            <%= link_to "Tasks", tasks_path, method: :get, class:"nav-link" %>
          </div>
          <div>
            <%= link_to "Project", projects_path, method: :get, class:"nav-link" %>
          </div>
          <div> 
            <%= link_to 'Search Task', search_tasks_path, method: :get, class:"text-success nav-link" if !admin? %>
          </div>
          <div>
            <%= link_to 'Admin', admin_path, method: :get, class:"text-success nav-link" if admin? %>
          </div>
        </div>
      </div>
    </ul>
    <div class="media">
      <img src="<%= asset_path "org_profile.jpeg" %>" class="mr-3 img-fluid" alt="sample-image">
    </div>
    <div class="d-flex align-items-center ml-3">
      <% if admin? %>
        <div>Logged in </div>
        <%= link_to "Admin" , admin_path, method: :get, class: "text-success ml-1" %>
        <div class="dropdown ml-4">
          <button type="button" id="dropdown1"
            class="btn-sm btn-primary dropdown-toggle"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
            Menu
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <div>
            <%= link_to "ログアウト" , login_path, method: :delete, class: "text-danger" %>
            </div>
          </div>
        </div>
      <% else %>
        <div>Logged in</div>
        <%= link_to current_user.name, users_path, method: :get, class:"nav-link font-weight-bold" %>
        <div class="dropdown ml-4">
          <button type="button" id="dropdown1"
              class="btn-sm btn-primary dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false">
            Menu
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <div>
              <% if current_user.name == 'guest' %>
                <%= link_to "ユーザーログイン" , login_index_path, method: :get, class: "dropdown-item" %>
              <% else %>
                <%= link_to "ログアウト" , login_path, method: :delete, class: "text-danger dropdown-item" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/head/_header_bar.html.erb
<% if !guest? || !logged_in? %>
  <div class="container mt-2 mb-3" style="height: 40px;">
    <div class="row text-center">
      <div class="col-sm-4">
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to "Todo", tasks_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to "complete", completed_tasks_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to "deleted", deleted_tasks_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>